Import( 'project', 'libs' )

# Temporarily disabled
#
#project.UnitTest(
#	target = ['sequenceParser'] + project.getDirs(),
#	dirs = ['.'],
#	libraries = [
#		libs.sequenceParser,
#		libs.boost_unit_test_framework,
#		]
#	)

