Import( 'project', 'libs' )

project.ScriptTests(
		target = 'sequenceParser',
		dirs = ['.'],
		libraries = [libs.pySequenceParser],
		procEnvFlags = {
			'PYTHONPATH': project.inOutputDir('python'),
			'OFX_PLUGIN_PATH': project.inOutputPlugin(),
			},
	)

